# Generated by Django 4.1.2 on 2022-10-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_subscribedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1', models.ImageField(blank=True, null=True, upload_to='')),
                ('im2', models.ImageField(blank=True, null=True, upload_to='')),
                ('im3', models.ImageField(blank=True, null=True, upload_to='')),
                ('im4', models.ImageField(blank=True, null=True, upload_to='')),
                ('productdet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
