# Generated by Django 4.1.2 on 2022-10-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
