# Generated by Django 4.1.2 on 2022-10-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productdetail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='productdet',
            new_name='product',
        ),
    ]
